### ISSUE TITLE
文档目录失效

### ISSUE THREAD

**Issue by pengyunshan** [keras-team/keras-docs-zh#100]
![image](https://user-images.githubusercontent.com/12589261/149491821-61487975-c202-46df-8ff7-18ca93cc8bf8.png)
没人管了吗？左侧目录失效，点不了，看起来好难受啊

**Comment by EnderOcelot** [comment]
> ![image](https://user-images.githubusercontent.com/12589261/149491821-61487975-c202-46df-8ff7-18ca93cc8bf8.png) 没人管了吗？左侧目录失效，点不了，看起来好难受啊

https://github.com/keras-team/keras-docs-zh/archive/refs/heads/master.zip
网页被人操作了，下载该链接下的md文档就行

**Comment by EnderOcelot** [comment]
> ![image](https://user-images.githubusercontent.com/12589261/149491821-61487975-c202-46df-8ff7-18ca93cc8bf8.png) 没人管了吗？左侧目录失效，点不了，看起来好难受啊

如果方便阅读也可以浏览https://keras-zh.readthedocs.io/

**Comment by pengyunshan** [comment]
> > ![image](https://user-images.githubusercontent.com/12589261/149491821-61487975-c202-46df-8ff7-18ca93cc8bf8.png) 没人管了吗？左侧目录失效，点不了，看起来好难受啊
> 
> 如果方便阅读也可以浏览https://keras-zh.readthedocs.io/

谢谢，https://keras-zh.readthedocs.io/ 可以了~
