### ISSUE TITLE
We need to follow the English document, would you like to contribute?

### ISSUE THREAD

**Issue by gaussic** [keras-team/keras-docs-zh#53]
We need to follow the English document recently, would you like to contribute?

Currently, these files need to be updates:

|    English    |    Chinese    |    GitHub    |    Description    |  Currently Translating | 
|  ---------   |  ----------- |  ---------------  | --------------- |  --------------- |
| ~~[Keras FAQ: Frequently Asked Keras Questions](https://keras.io/getting-started/faq/)~~ |  [Keras FAQ: 常见问题解答](https://keras.io/zh/getting-started/faq/) | [faq.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/getting-started/faq.md) | Some links need to be fixed, and some paragraphs need to be added. | [jiemojiemo](https://github.com/jiemojiemo) |
| ~~[Core Layers](https://keras.io/layers/core/)~~ | [核心网络层](https://keras.io/zh/layers/core/) | [core.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/layers/core.md) | Flatten, Input, SpatialDropout1D, SpatialDropout2D, SpatialDropout3D | [jiemojiemo](https://github.com/jiemojiemo) |
| ~~[Convolutional Layers](https://keras.io/layers/convolutional/)~~ | [卷积层](https://keras.io/zh/layers/convolutional/) | [convolutional.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/layers/convolutional.md) | SeparableConv1D | [King-HAW](https://github.com/King-HAW) |
| ~~[Pooling Layers](https://keras.io/layers/pooling/)~~ | [池化层](https://keras.io/zh/layers/pooling/) | [pooling.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/layers/pooling.md) | GlobalMaxPooling3D, GlobalAveragePooling3D | [King-HAW](https://github.com/King-HAW)  |
| ~~[Recurrent Layers](https://keras.io/layers/recurrent/)~~ | [循环层](https://keras.io/zh/layers/recurrent/) | [recurrent.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/layers/recurrent.md) | GRU, ~~StackedRNNCells~~ | [King-HAW](https://github.com/King-HAW)  |
| ~~[Advanced Activations Layers](https://keras.io/layers/advanced-activations/)~~ | [高级激活层](https://keras.io/zh/layers/advanced-activations/) | [advanced-activations.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/layers/advanced-activations.md) | ReLU |  [desti-nation](https://github.com/desti-nation) |
| ~~[Optimizers](https://keras.io/optimizers/)~~ | [优化器](https://keras.io/zh/optimizers/) | [optimizers.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/optimizers.md) | Adagrad, Adadelta | [King-HAW](https://github.com/King-HAW) |
| ~~[Activations](https://keras.io/activations/)~~ | [激活函数](https://keras.io/zh/activations/) | [activations.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/activations.md) | Total page | [jiemojiemo](https://github.com/jiemojiemo) |
| [Callbacks](https://keras.io/callbacks/) | [回调函数](https://keras.io/zh/callbacks/) | [callbacks.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/callbacks.md) | TerminateOnNaN, BaseLogger, ProgbarLogger, RemoteMonitor, TensorBoard | |
| [Applications](https://keras.io/applications/) | [应用](https://keras.io/zh/applications/) | [applications.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/applications.md) | Add MobileNetV2, and adjust the whole page. | |
| [Backend](https://keras.io/backend/) | [后端](https://keras.io/zh/backend/) | [backend.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/backend.md) | is_tensor, slice | |
| ~~[Regularizers](https://keras.io/regularizers/)~~ | [正正则化](https://keras.io/zh/regularizers/) | [regularizers.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/regularizers.md) | Adjust the whole page. |  [sighsmile](https://github.com/sighsmile) |
| ~~[Constraints](https://keras.io/constraints/)~~ | [约束项](https://keras.io/zh/constraints/) | [constraints.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/constraints.md) | Adjust the whole page. |  [sighsmile](https://github.com/sighsmile) |
| ~~[Utils](https://keras.io/utils/)~~ | [工具](https://keras.io/zh/utils/) | [utils.md](https://github.com/keras-team/keras-docs-zh/blob/master/sources/utils.md) | multi_gpu_model |  [desti-nation](https://github.com/desti-nation) |

Contributions are welcome. 

If you wanna contribute, please reply to this issue directly, we will mark you in this table. Thanks.

**Comment by desti-nation** [comment]
我认领 
Advanced Activations Layers | 高级激活层 | advanced-activations.md | ReLU

**Comment by desti-nation** [comment]
认领
Constraints | 约束项 | constraints.md | Adjust the whole page. |  
Utils | 工具 | utils.md | multi_gpu_model

**Comment by desti-nation** [comment]
认领
Utils | 工具 | utils.md | multi_gpu_model

**Comment by King-HAW** [comment]
Claim
Pooling Layers | 池化层 | pooling.md | GlobalMaxPooling3D, GlobalAveragePooling3D

**Comment by King-HAW** [comment]
Claim
Recurrent Layers | 循环层 | recurrent.md | GRU

**Comment by sighsmile** [comment]
Done regularizers.md and constraints.md.

**Comment by jiemojiemo** [comment]
Claim
Core Layers | 核心网络层 | core.md | Flatten, Input, SpatialDropout1D, SpatialDropout2D, SpatialDropout3D

**Comment by King-HAW** [comment]
Claim
Optimizers | 优化器 | optimizers.md

**Comment by King-HAW** [comment]
Claim
Optimizers | 优化器 | optimizers.md | Adagrad, Adadelta

**Comment by jiemojiemo** [comment]
Claim
activations.md | Total page
