### ISSUE TITLE
Docs » Layers » 卷积层 Convolutional

### ISSUE THREAD

**Issue by LittlePandaSea** [keras-team/keras-docs-zh#69]
The introduction of Convolutional Layers Conv1D:

参数:
padding: "valid", "causal" 或 "same" 之一 (大小写敏感) "valid" 表示「不填充」。 "same" 表示填充输入以使输出具有与原始输入相同的长度。 "causal" 表示因果（膨胀）卷积， 例如，output[t] 不依赖于 input[t+1:]， 在模型不应违反时间顺序的时间数据建模时非常有用。 在模型不应违反时间顺序的时间数据建模时非常有用。 详见 WaveNet: A Generative Model for Raw Audio, section 2.1。

The sentence of “在模型不应违反时间顺序的时间数据建模时非常有用。” is repeated.

**Comment by gaussic** [comment]
Thanks, fixed.
