### ISSUE TITLE
关于backend里的函数翻译很不严谨，返回类型tf.variable、tf.tensor、keras tensor混乱不清。感觉就是程序源码注释里的翻译；eval()应该是计算，翻译成估计

### ISSUE THREAD

**Issue by zhaoyun0071** [keras-team/keras-docs-zh#90]
关于backend里的函数翻译很不严谨，返回类型tf.variable、tf.tensor、keras tensor混乱不清。感觉就是程序源码注释里的翻译；eval()应该是计算，翻译成估计

**Comment by gaussic** [comment]
具体是哪里，还望指出。

eval以官方原版英文为准：

```
Evaluates the value of a tensor.
```

**Comment by zhaoyun0071** [comment]
> 具体是哪里，还望指出。
> 
> eval以官方原版英文为准：
> 
> ```
> Evaluates the value of a tensor.
> ```

evaluate：evaluate是数学用语，指“求…的值”，引申指用比较熟悉的表示法评估某事物的价值。

**Comment by gaussic** [comment]
谢谢，在此保留原观点
