### ISSUE TITLE
为啥官网的文档不更新而要在 readthedocs.io 上建文档?

### ISSUE THREAD

**Issue by GF-Huang** [keras-team/keras-docs-zh#92]
这些地方显示不正确也没人管。

![image](https://user-images.githubusercontent.com/4510984/97835181-8dc54800-1d14-11eb-882d-cac15b383f2c.png)

**Comment by gaussic** [comment]
目前翻译人员只能控制文档内容的部分，文档格式由原作者控制。
现在中文、日文、韩文版都有显示问题，我们之前也反馈了，但是没有得到回应，这就是开readthedocs的原因。
另外现在的Keras英文文档已和原来版本大不一样，所以估计原作者就对现在的翻译版本没有太上心。
所以，要看格式正确的文档，以readthedocs为准。

**Comment by GF-Huang** [comment]
明白，感谢你们翻译。
